name: CD

permissions:
  id-token: write # required to use OIDC authentication
  contents: read

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  cd:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get CI Workflow Run ID
        run: echo "CI_RUN_ID=${{ github.event.workflow_run.id }}" >> $GITHUB_ENV

      - name: Download CDK output
        uses: actions/download-artifact@v4
        with:
          name: cdk-output
          path: cdk.out
          github-token: ${{ secrets.GH_PAT }} # token with actions:read permissions on target repo
          repository: "${GITHUB_ACTION_REPOSITORY}"
          run-id: "${{ env.CI_RUN_ID }}"

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: AWS Assume deployer role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::764157184418:role/terraform-aws-klim-personal-github-manual"
          role-duration-seconds: 3600
          role-skip-session-tagging: true
          aws-region: "us-east-1"

      - name: CDK deploy
        run: cdk deploy -all --require-approval never

